// <auto-generated />
using System;
using FCG.Users.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FCG.Users.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260108223947_primaryMigration")]
    partial class primaryMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FCG.Users.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ISN_USUARIO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DTH_CRIACAO");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DTH_ATUALIZACAO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1000)")
                        .HasColumnName("DSC_SENHA");

                    b.Property<string>("Passoword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("INT")
                        .HasColumnName("ISN_GRUPO_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("UserGroupId");

                    b.ToTable("TB_USUARIO", (string)null);
                });

            modelBuilder.Entity("FCG.Users.Domain.Entities.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ISN_GRUPO_USUARIO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DTH_CRIACAO");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DTH_ATUALIZACAO");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("DSC_GRUPO");

                    b.HasKey("Id");

                    b.ToTable("TB_GRUPO_USUARIO", (string)null);
                });

            modelBuilder.Entity("FCG.Users.Domain.Entities.User", b =>
                {
                    b.HasOne("FCG.Users.Domain.Entities.UserGroup", "UserGroup")
                        .WithMany("Users")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("FCG.Users.Domain.Entities.UserGroup", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
