apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-fcg-prod-253
  namespace: fcg-prod
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<COLE_AQUI_O_CSI_CLIENT_ID>"

    keyvaultName: "kv-fcg-prod-2532"
    tenantId: "8d75f1ef-d0ba-4752-be44-dbcf36105322"
    objects: |
      array:
        - |
          objectName: usersapi-connectionstrings-connectionstrings
          objectType: secret
        - |
          objectName: usersapi-jwt-issuer
          objectType: secret
        - |
          objectName: usersapi-jwt-key
          objectType: secret
        - |
          objectName: rabbitmq-password
          objectType: secret

  secretObjects:
    - secretName: users-api-secret
      type: Opaque
      data:
        - objectName: usersapi-connectionstrings-connectionstrings
          key: CONNECTIONSTRINGS__CONNECTIONSTRINGS
        - objectName: usersapi-jwt-issuer
          key: JWT__ISSUER
        - objectName: usersapi-jwt-key
          key: JWT__KEY
        - objectName: rabbitmq-password
          key: RABBITMQ__PASSWORD
