apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: usersapi-kv
  namespace: fcg-prod
spec:
  provider: azure
  parameters:
    keyvaultName: "kv-fcg-prod-2532"
    tenantId: "8d75f1ef-d0ba-4752-be44-dbcf36105322"
    objects: |
      array:
        - |
          objectName: usersapi-connectionstrings-connectionstrings
          objectType: secret
        - |
          objectName: usersapi-jwt-issuer
          objectType: secret
        - |
          objectName: usersapi-jwt-key
          objectType: secret
        - |
          objectName: usersapi-rabbitmq-password
          objectType: secret

  # ✅ Sync para Kubernetes Secret com as KEYS exatas que seu Deployment usa
  secretObjects:
    - secretName: users-api-secret
      type: Opaque
      data:
        - objectName: usersapi-connectionstrings-connectionstrings
          key: CONNECTIONSTRINGS__CONNECTIONSTRINGS
        - objectName: usersapi-jwt-issuer
          key: JWT__ISSUER
        - objectName: usersapi-jwt-key
          key: JWT__KEY
        - objectName: usersapi-rabbitmq-password
          key: RABBITMQ__PASSWORD
