apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-fcg-prod-253
  namespace: fcg-prod
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "6199a0e8-5daf-40f8-88db-3622e2466d6a"

    keyvaultName: "kv-fcg-prod-253"
    tenantId: "8d75f1ef-d0ba-4752-be44-dbcf36105322"
    objects: |
      array:
        - |
          objectName: users-connectionstrings-connectionstrings
          objectType: secret
        - |
          objectName: jwt-issuer
          objectType: secret
        - |
          objectName: jwt-key
          objectType: secret
        - |
          objectName: redis-connectionstring
          objectType: secret
        - |
          objectName: servicebus-connectionstring
          objectType: secret
        - |
          objectName: mongodbsql-connectionstring
          objectType: secret
        - |
          objectName: applicationinsights-connectionstring
          objectType: secret

  secretObjects:
    - secretName: users-api-secret
      type: Opaque
      data:
        - objectName: users-connectionstrings-connectionstrings
          key: CONNECTIONSTRINGS__CONNECTIONSTRINGS
        - objectName: jwt-issuer
          key: JWT__ISSUER
        - objectName: jwt-key
          key: JWT__KEY
        - objectName: redis-connectionstring
          key: REDIS__CONNECTIONSTRING
        - objectName: servicebus-connectionstring
          key: SERVICEBUS__CONNECTIONSTRING
        - objectName: mongodbsql-connectionstring
          key: MONGODBSQL__CONNECTIONSTRING
        - objectName: applicationinsights-connectionstring
          key: APPLICATIONINSIGHTS_CONNECTIONSTRING
